### ISSUE TITLE
Solo的编码，Webrtc中使用什么解码器可以解码

### ISSUE THREAD

**Issue by DyncEric** [AgoraIO-Community/Solo#9]
RT，Thanks

**Comment by plutoless** [comment]
您是说浏览器上怎么选择solo做解码吗?

**Comment by DyncEric** [comment]
嗯嗯，是的

**Comment by plutoless** [comment]
这个目前做不到哦，浏览器的解码器是固定的

**Comment by DyncEric** [comment]
我看到时说的是支持webrtc的，这个该怎么理解呀

Agora SOLO（以下简称“SOLO”）是由声网Agora自主研发的一款面向不稳定网络的音频编解码器。

更重要的是，SOLO 编解码器兼容WebRTC。如果开发者正在基于 WebRTC 开发自己的应用，可将 SOLO 集成到其中。WebRTC 默认使用的是 Opus 作为编解码器，而 Silk 与 Opus 有千丝万缕的联系，我们曾经在RTC 专栏的一篇投稿中讲过。而 SOLO 则是以 Silk 为基础，融合了带宽扩展(BWE)和多描述编码(MDC)等技术，使其能在较低复杂度下拥有弱网对抗能力。也就是说，在 SOLO 的帮助下， WebRTC 应用可以更好地应对不稳定的网络环境，对音频质量与体验带来有效的保障与提升。

**Comment by jonestorrons** [comment]
> 我看到时说的是支持webrtc的，这个该怎么理解呀
> 
> Agora SOLO（以下简称“SOLO”）是由声网Agora自主研发的一款面向不稳定网络的音频编解码器。
> 
> 更重要的是，SOLO 编解码器兼容WebRTC。如果开发者正在基于 WebRTC 开发自己的应用，可将 SOLO 集成到其中。WebRTC 默认使用的是 Opus 作为编解码器，而 Silk 与 Opus 有千丝万缕的联系，我们曾经在RTC 专栏的一篇投稿中讲过。而 SOLO 则是以 Silk 为基础，融合了带宽扩展(BWE)和多描述编码(MDC)等技术，使其能在较低复杂度下拥有弱网对抗能力。也就是说，在 SOLO 的帮助下， WebRTC 应用可以更好地应对不稳定的网络环境，对音频质量与体验带来有效的保障与提升。

原生的webrtc是不可以的，基于webrtc做二次开发时，需要将解码器和相关码流处理逻辑集成进webrtc，集成方法可以参考readme。

**Comment by DyncEric** [comment]
好的，明白了。谢谢
